-- Tabla de autores
CREATE TABLE autores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    imagen VARCHAR(255)
);

-- Tabla de posts
CREATE TABLE posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT NOT NULL,
    fecha_creacion DATETIME DEFAULT CURRENT_TIMESTAMP,
    categoria VARCHAR(100),
    autor_id INT NOT NULL,
    FOREIGN KEY (autor_id) REFERENCES autores(id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


INSERT INTO autores (nombre, email, imagen) VALUES
('Autor_1', 'autor1@example.com', 'autor1.jpg'),
('Autor_2', 'autor2@example.com', 'autor2.jpg'),
('Autor_3', 'autor3@example.com', 'autor3.jpg'),
('Autor_4', 'autor4@example.com', 'autor4.jpg'),
('Autor_5', 'autor5@example.com', 'autor5.jpg'),
('Autor_6', 'autor6@example.com', 'autor6.jpg'),
('Autor_7', 'autor7@example.com', 'autor7.jpg'),
('Autor_8', 'autor8@example.com', 'autor8.jpg'),
('Autor_9', 'autor9@example.com', 'autor9.jpg'),
('Autor_10', 'autor10@example.com', 'autor10.jpg');


INSERT INTO posts (titulo, descripcion, categoria, autor_id) VALUES
('Post_1_de_Autor_1', 'Descripción del post 1 del autor 1', 'Tecnología', 1),
('Post_2_de_Autor_1', 'Descripción del post 2 del autor 1', 'Ciencia', 1),
('Post_3_de_Autor_1', 'Descripción del post 3 del autor 1', 'Arte', 1),
('Post_4_de_Autor_1', 'Descripción del post 4 del autor 1', 'Historia', 1),
('Post_5_de_Autor_1', 'Descripción del post 5 del autor 1', 'Tecnología', 1),
('Post_6_de_Autor_1', 'Descripción del post 6 del autor 1', 'Ciencia', 1),
('Post_7_de_Autor_1', 'Descripción del post 7 del autor 1', 'Arte', 1),
('Post_8_de_Autor_1', 'Descripción del post 8 del autor 1', 'Historia', 1),
('Post_9_de_Autor_1', 'Descripción del post 9 del autor 1', 'Tecnología', 1),
('Post_10_de_Autor_1', 'Descripción del post 10 del autor 1', 'Ciencia', 1),
('Post_1_de_Autor_2', 'Descripción del post 1 del autor 2', 'Tecnología', 2),
('Post_2_de_Autor_2', 'Descripción del post 2 del autor 2', 'Ciencia', 2),
('Post_3_de_Autor_2', 'Descripción del post 3 del autor 2', 'Arte', 2),
('Post_4_de_Autor_2', 'Descripción del post 4 del autor 2', 'Historia', 2),
('Post_5_de_Autor_2', 'Descripción del post 5 del autor 2', 'Tecnología', 2),
('Post_6_de_Autor_2', 'Descripción del post 6 del autor 2', 'Ciencia', 2),
('Post_7_de_Autor_2', 'Descripción del post 7 del autor 2', 'Arte', 2),
('Post_8_de_Autor_2', 'Descripción del post 8 del autor 2', 'Historia', 2),
('Post_9_de_Autor_2', 'Descripción del post 9 del autor 2', 'Tecnología', 2),
('Post_10_de_Autor_2', 'Descripción del post 10 del autor 2', 'Ciencia', 2),
('Post_1_de_Autor_3', 'Descripción del post 1 del autor 3', 'Tecnología', 3),
('Post_2_de_Autor_3', 'Descripción del post 2 del autor 3', 'Ciencia', 3),
('Post_3_de_Autor_3', 'Descripción del post 3 del autor 3', 'Arte', 3),
('Post_4_de_Autor_3', 'Descripción del post 4 del autor 3', 'Historia', 3),
('Post_5_de_Autor_3', 'Descripción del post 5 del autor 3', 'Tecnología', 3),
('Post_6_de_Autor_3', 'Descripción del post 6 del autor 3', 'Ciencia', 3),
('Post_7_de_Autor_3', 'Descripción del post 7 del autor 3', 'Arte', 3),
('Post_8_de_Autor_3', 'Descripción del post 8 del autor 3', 'Historia', 3),
('Post_9_de_Autor_3', 'Descripción del post 9 del autor 3', 'Tecnología', 3),
('Post_10_de_Autor_3', 'Descripción del post 10 del autor 3', 'Ciencia', 3),
('Post_1_de_Autor_4', 'Descripción del post 1 del autor 4', 'Tecnología', 4),
('Post_2_de_Autor_4', 'Descripción del post 2 del autor 4', 'Ciencia', 4),
('Post_3_de_Autor_4', 'Descripción del post 3 del autor 4', 'Arte', 4),
('Post_4_de_Autor_4', 'Descripción del post 4 del autor 4', 'Historia', 4),
('Post_5_de_Autor_4', 'Descripción del post 5 del autor 4', 'Tecnología', 4),
('Post_6_de_Autor_4', 'Descripción del post 6 del autor 4', 'Ciencia', 4),
('Post_7_de_Autor_4', 'Descripción del post 7 del autor 4', 'Arte', 4),
('Post_8_de_Autor_4', 'Descripción del post 8 del autor 4', 'Historia', 4),
('Post_9_de_Autor_4', 'Descripción del post 9 del autor 4', 'Tecnología', 4),
('Post_10_de_Autor_4', 'Descripción del post 10 del autor 4', 'Ciencia', 4),
('Post_1_de_Autor_5', 'Descripción del post 1 del autor 5', 'Tecnología', 5),
('Post_2_de_Autor_5', 'Descripción del post 2 del autor 5', 'Ciencia', 5),
('Post_3_de_Autor_5', 'Descripción del post 3 del autor 5', 'Arte', 5),
('Post_4_de_Autor_5', 'Descripción del post 4 del autor 5', 'Historia', 5),
('Post_5_de_Autor_5', 'Descripción del post 5 del autor 5', 'Tecnología', 5),
('Post_6_de_Autor_5', 'Descripción del post 6 del autor 5', 'Ciencia', 5),
('Post_7_de_Autor_5', 'Descripción del post 7 del autor 5', 'Arte', 5),
('Post_8_de_Autor_5', 'Descripción del post 8 del autor 5', 'Historia', 5),
('Post_9_de_Autor_5', 'Descripción del post 9 del autor 5', 'Tecnología', 5),
('Post_10_de_Autor_5', 'Descripción del post 10 del autor 5', 'Ciencia', 5),
('Post_1_de_Autor_6', 'Descripción del post 1 del autor 6', 'Tecnología', 6),
('Post_2_de_Autor_6', 'Descripción del post 2 del autor 6', 'Ciencia', 6),
('Post_3_de_Autor_6', 'Descripción del post 3 del autor 6', 'Arte', 6),
('Post_4_de_Autor_6', 'Descripción del post 4 del autor 6', 'Historia', 6),
('Post_5_de_Autor_6', 'Descripción del post 5 del autor 6', 'Tecnología', 6),
('Post_6_de_Autor_6', 'Descripción del post 6 del autor 6', 'Ciencia', 6),
('Post_7_de_Autor_6', 'Descripción del post 7 del autor 6', 'Arte', 6),
('Post_8_de_Autor_6', 'Descripción del post 8 del autor 6', 'Historia', 6),
('Post_9_de_Autor_6', 'Descripción del post 9 del autor 6', 'Tecnología', 6),
('Post_10_de_Autor_6', 'Descripción del post 10 del autor 6', 'Ciencia', 6),
('Post_1_de_Autor_7', 'Descripción del post 1 del autor 7', 'Tecnología', 7),
('Post_2_de_Autor_7', 'Descripción del post 2 del autor 7', 'Ciencia', 7),
('Post_3_de_Autor_7', 'Descripción del post 3 del autor 7', 'Arte', 7),
('Post_4_de_Autor_7', 'Descripción del post 4 del autor 7', 'Historia', 7),
('Post_5_de_Autor_7', 'Descripción del post 5 del autor 7', 'Tecnología', 7),
('Post_6_de_Autor_7', 'Descripción del post 6 del autor 7', 'Ciencia', 7),
('Post_7_de_Autor_7', 'Descripción del post 7 del autor 7', 'Arte', 7),
('Post_8_de_Autor_7', 'Descripción del post 8 del autor 7', 'Historia', 7),
('Post_9_de_Autor_7', 'Descripción del post 9 del autor 7', 'Tecnología', 7),
('Post_10_de_Autor_7', 'Descripción del post 10 del autor 7', 'Ciencia', 7),
('Post_1_de_Autor_8', 'Descripción del post 1 del autor 8', 'Tecnología', 8),
('Post_2_de_Autor_8', 'Descripción del post 2 del autor 8', 'Ciencia', 8),
('Post_3_de_Autor_8', 'Descripción del post 3 del autor 8', 'Arte', 8),
('Post_4_de_Autor_8', 'Descripción del post 4 del autor 8', 'Historia', 8),
('Post_5_de_Autor_8', 'Descripción del post 5 del autor 8', 'Tecnología', 8),
('Post_6_de_Autor_8', 'Descripción del post 6 del autor 8', 'Ciencia', 8),
('Post_7_de_Autor_8', 'Descripción del post 7 del autor 8', 'Arte', 8),
('Post_8_de_Autor_8', 'Descripción del post 8 del autor 8', 'Historia', 8),
('Post_9_de_Autor_8', 'Descripción del post 9 del autor 8', 'Tecnología', 8),
('Post_10_de_Autor_8', 'Descripción del post 10 del autor 8', 'Ciencia', 8),
('Post_1_de_Autor_9', 'Descripción del post 1 del autor 9', 'Tecnología', 9),
('Post_2_de_Autor_9', 'Descripción del post 2 del autor 9', 'Ciencia', 9),
('Post_3_de_Autor_9', 'Descripción del post 3 del autor 9', 'Arte', 9),
('Post_4_de_Autor_9', 'Descripción del post 4 del autor 9', 'Historia', 9),
('Post_5_de_Autor_9', 'Descripción del post 5 del autor 9', 'Tecnología', 9),
('Post_6_de_Autor_9', 'Descripción del post 6 del autor 9', 'Ciencia', 9),
('Post_7_de_Autor_9', 'Descripción del post 7 del autor 9', 'Arte', 9),
('Post_8_de_Autor_9', 'Descripción del post 8 del autor 9', 'Historia', 9),
('Post_9_de_Autor_9', 'Descripción del post 9 del autor 9', 'Tecnología', 9),
('Post_10_de_Autor_9', 'Descripción del post 10 del autor 9', 'Ciencia', 9),
('Post uno de autor 10', 'Descripción del post 1 del autor 10', 'Tecnologí1a', 10),
('Post_2_de_Autor_10', 'Descripción del post 2 del autor 10', 'Ciencia', 10),
('Post_3_de_Autor_10', 'Descripción del post 3 del autor 10', 'Arte', 10),
('Post_4_de_Autor_10', 'Descripción del post 4 del autor 10', 'Historia', 10),
('Post_5_de_Autor_10', 'Descripción del post 5 del autor 10', 'Tecnología', 10),
('Post_6_de_Autor_10', 'Descripción del post 6 del autor 10', 'Ciencia', 10),
('Post_7_de_Autor_10', 'Descripción del post 7 del autor 10', 'Arte', 10),
('Post_8_de_Autor_10', 'Descripción del post 8 del autor 10', 'Historia', 10),
('Post_9_de_Autor_10', 'Descripción del post 9 del autor 10', 'Tecnología', 10),
('Post_10_de_Autor_10', 'Descripción del post 10 del autor 10', 'Ciencia', 10);